### ISSUE TITLE
NonNumericResponseException while executing command [VIN], response []

### ISSUE THREAD

**Issue by RobertSzekely** [eltonvs/kotlin-obd-api#14]
I get the same exception if I run the Speed or the EngineRpm commands. Do you have any idea what's causing this issue? I'm using version 1.1.1 of the library

<img width="917" alt="Screenshot 2021-10-12 at 17 01 42" src="https://user-images.githubusercontent.com/17162302/136970998-65cd19f7-0550-4d29-9b1c-b7c5ae3ba221.png">

**Comment by eltonvs** [comment]
Hey!

Version [1.2.0](https://github.com/eltonvs/kotlin-obd-api/releases/tag/v1.1.2) was just released and it should fix this issue.
