### ISSUE TITLE
NonNumericResponse Exception 1.2.0

### ISSUE THREAD

**Issue by JuanJoseMoralesCalvo** [eltonvs/kotlin-obd-api#21]
Im getting the same error that was fix in version 1.1.2 when trying the speed command.
Just to make sure im installing the 1.2.0 version great im implementing on dependencies implementation 'com.github.eltonvs:kotlin-obd-api:1.2.0' and on setting.graddle im establishing  maven { url 'https://jitpack.io' }.
The bluetooth connection is established correctly but when i send this commands it throws the exception.

Did i install the libraries correctly? I also tried to add the jar file and delete the line  'com.github.eltonvs:kotlin-obd-api:1.2.0' but it happens the same exception so im a bit lost.

@eltonvs 

Thanks in advance.

**Comment by chubecode** [comment]
same here..

**Comment by FerranFuentes** [comment]
I encountered the same problem while using version 1.2.0.

**Comment by cliffgr** [comment]
The issue is still there? or you found a workaround?

**Comment by JuanJoseMoralesC** [comment]
I reccomend using the lm327 documentation, its not dificult just to make some functions like reading Speed and fuel.

**Comment by FerranFuentes** [comment]
> The issue is still there? or you found a workaround?

Just switched to other APIs based on Java. Completly compatible with my Kotlin code so far and the data collection is working fine.

**Comment by Meriemi-git** [comment]
This only append on first command because inputStream have no available bytes to read.
I send a PR to fix this.

**Comment by eltonvs** [comment]
This issue should now be resolved as version 1.3.0 was released.
