### ISSUE TITLE
OBDRawResponse -> value: Wrong conversion?

### ISSUE THREAD

**Issue by NuriB68** [eltonvs/kotlin-obd-api#28]
Hello guys,
The output of my OBD Commands dont match the reality when requesting the value of it. In case of the OBDRawResponses however the output seems correct. 
Here is a comparison of the value and raw response for RPM and Vehicle Speed.

 `val obdConnection = ObdDeviceConnection(inputStream, outputStream)         `
` val response = obdConnection.run(RPMCommand())`
` val output = response.value`
` Log.i("data", "RPM: $output")`

**RPM with real RPM of 0**                
response.value: 
`RPM: 272826368`
response.rawResponse: 
`RPM: ObdRawResponse(value=01 0C41 0C 00 00, elapsedTime=320)`

**VehicleSpeed with real speed of 0**
response.value: 
`Speed: 65`
response.rawResponse: 
`Speed: ObdRawResponse(value=01 0D41 0D 00, elapsedTime=319)`

When manually converting the raw response this seems to be correct. But for response.value i cant figure out why i get those strange values. Seems like the API doesnt convert the raw response correctly. 
Can someone help me out to fix this issue?

**Comment by gabrik** [comment]
Hi @NuriB68 ,

I'm having the same issue how did you solve it?

I mean I have exactly the same issue:

```
2023-12-29 13:31:57.683 15992-18608 MyApp::MainFragment io.xxx.xxx                  V  Speed 65 Km/h - ObdRawResponse(value=01 0D410D84, elapsedTime=510)
2023-12-29 13:31:58.451 15992-18608 MyApp::MainFragment io.xxx.xxx                   V  Speed 65 Km/h - ObdRawResponse(value=01 0D410DB8, elapsedTime=510)
2023-12-29 13:31:59.214 15992-18608 MyApp::MainFragment io.xxx.xxx                 V  Speed 65 Km/h - ObdRawResponse(value=01 0D410D80, elapsedTime=509)
2023-12-29 13:31:59.990 15992-18608 MyApp::MainFragment io.xxx.xxx                   V  Speed 65 Km/h - ObdRawResponse(value=01 0D410D11, elapsedTime=516)
```


With this code:
```
val response = obdConnection.run(SpeedCommand())
Log.v(TAG, "Speed ${response.value} ${response.unit} - ${response.rawResponse}")

```

And device initialized like:

```
 "ATD", // Set ELM327 to default
 "ATZ", // Reset ODB parameters
 "ATE0", // Echo Off
 "ATL0", // Linefeed Off
 "ATS0", // Spaces Off
 "ATH0", // Headers Off
 "ATAL", // Allow long messages (>7bytes)
 "ATAT1", // Set adaptive timing 1
"ATSTFF", // Set timeout to maximum
 "ATSP0", // Automatic Protocol selection
"ATSS", // Default Protocol search list
 ```

**Comment by gabrik** [comment]
I found out why.

After reading the ELM327 datasheet I discovered that I need to send the carriage return `\r` after each command, otherwise it will not be taken into account by the device.

So it was not being configured correctly.

Adding the `\r` solved the issue.
Also, I'm emptying the receiving buffer so that when the real data comes it will be read immediately.

**Comment by NuriB68** [comment]
> I found out why.
> 
> After reading the ELM327 datasheet I discovered that I need to send the carriage return `\r` after each command, otherwise it will not be taken into account by the device.
> 
> So it was not being configured correctly.
> 
> Adding the `\r` solved the issue. Also, I'm emptying the receiving buffer so that when the real data comes it will be read immediately.

Hey gabrik,
interesting solution. In my case the issue was, that i didn't know that the Adapter has to be initialized each time i connect it with the car. I thought the AT Commands are saved and therefore did it only once.
So the first time doing the initialization manually via another Elm terminal App i got correct responds, but afterwards the issue came.

So i solved the issue by Always having an initialization Routine when my App connects to the Adapter, no Matter if it is already initialized or not.
