### ISSUE TITLE
Where is the release jar file?

### ISSUE THREAD

**Issue by lhtdeg** [eltonvs/kotlin-obd-api#5]
i can't find a jar file from Github's releases page,there is only source code in there.And also, i can't find any user interface code in source code ,Did I make a mistake? Thanks.

**Comment by eltonvs** [comment]
Hey @lhtdeg thanks for pointing this out, I forgot linking the jar files there, but just did it :)
There's no user interface here, this is just the API, so you can build an application on top of it, I'm thinking in release later a simple android app using this library.

**Comment by lhtdeg** [comment]
My car is Mitsubishi Outlander,i‘m trying to change my In-Vehicle Infotainment .I want to add vehicle information display from bluetooth OBD adapter,so I found this great library.Thank you for your hard work.
