### ISSUE TITLE
NonNumericResponseException while executing command [SPEED], response []

### ISSUE THREAD

**Issue by DoronShaul** [eltonvs/kotlin-obd-api#7]
Hi Elton,
i'm trying to use your library in my android project.  my project is in java, but i created a kotlin class for your library.
here is my kotlin class:
![obdThread](https://user-images.githubusercontent.com/44787567/92396641-069d8e80-f12e-11ea-8260-79808b142dcd.jpg)

everytime i run this code it gives me a NonNumericResponseException. it happens with all of the commands.
can you please help me?

Thanks, Doron.

**Comment by Lucastmarques** [comment]
Hi Doron and Elton,
I am experiencing the same problem. Please, tell me if you get any clue, Doron.
Thanks, Lucas.

**Comment by eltonvs** [comment]
Hey @DoronShaul and @Lucastmarques I went over this issue this weekend and was able to confirm this is an issue.
I'm guessing this can be a release issue as the API is working properly in an app I developed before.

I'll continue looking further to resolve this ASAP. Feel free to share any findings.

**Comment by cliffgr** [comment]
Same issue here...

**Comment by eltonvs** [comment]
Hey!

Version [1.2.0](https://github.com/eltonvs/kotlin-obd-api/releases/tag/v1.1.2) was just released and it should fix this issue.

**Comment by chubecode** [comment]
issues still exist :(

**Comment by eltonvs** [comment]
This issue should now be resolved as version 1.3.0 was released.
